# Site
title:               Eliana Cudriz
bio:                'Mi compromiso con su negicio es crear junto con usted indicadores que permitan medir tu negocio de manera confiable, asegurando toma de decisiones a tiempo en pro del crecimiento de su negocio.
                     Con una informacion contable certera y oportuna lograremos el cumplimiento de sus metas. Juntos comprometidos en el éxito.'
quote:              'No hay éxito duradero sin compromiso (Tony Robbins)'
description:        'Profesional entusiasta por las NIIF, tributaria, auditoría y finanzas.'
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
alt_logo:           'Logo Eliana Cudriz'
profile:            'assets/img/foto.png'
alt_profile:        'Foto Eliana Cudriz'
background:         'assets/img/fondo.jpg'
alt_background:     'Laptop and notepad. Photo by Nick Morrison on Unsplash https://unsplash.com/photos/FHnnjk1Yj7Y'
notfound:           'assets/img/notfound.gif'
alt_notfound:       'pulp fiction john travolta not found from https://media.giphy.com/media/6uGhT1O4sxpi8/source.gif'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             es_MX
url:                https://ecudrizcontable.com

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   https-elianacudriz-github-io-ecudrizcontable

#email contact
not_found_subject: "[Error-Pagina]%20Pagina%20no%20encontrada"
not_found_body:    "Hola,%20parece%20que%20no%20pude%20encontrar%20la%20siguiente%20pagina: "
contact_subject:   "[Contacto] Oferta de servicios contables"
contact_body:      "Hola! Estoy interesado en conocer mas de tus servicios."

# MailChimp settings
mailchimp_action: https://github.us10.list-manage.com/subscribe/post?u=c3a5e2eb37d8f568e01d2bf1a&amp;id=eaf8f2083c
mailchimp_input: b_c3a5e2eb37d8f568e01d2bf1a_eaf8f2083c

whatsapp:
  number:         573053491660
  text:           "Hola! Estoy interesado en conocer mas de tus servicios."
# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
#  analytics:        UA-173577540-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              elianacudriz@gmail.com
twitter:            eliana_cudriz
facebook:           Eliana-Cudriz-101761994864692/
linkedin:           eliana-cudriz-53b82210b/
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          elianacudriz/?hl=en
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
